"""
Django settings for living_documents_server project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Stanford Core NLP server
NLP_SERVER_URL = 'http://130.203.136.198:9000/'
# NLP_SERVER_URL = 'http://lws-hanrahan.ist.psu.edu:4200/'
# NLP_SERVER_URL = 'http://living-documents.ist.psu.edu:4200/'
# NLP_SERVER_URL = 'http://130.203.136.198:4200'
# NLP_SERVER_URL = 'http://0.0.0.0:4200'

# Constant value used for pre-processing word to index
FAST_ABS_RL_SUMMARIZER_PAD = 0
FAST_ABS_RL_SUMMARIZER_UNK = 1
FAST_ABS_RL_SUMMARIZER_START = 2
FAST_ABS_RL_SUMMARIZER_END = 3
# Path to pretrained model, /new is the latest version, /acl is the paper version
FAST_ABS_RL_SUMMARIZER_MODEL_DIR = 'text_generation/summarizers/fast_abs_rl/pretrained/new/'
# FAST_ABS_RL_SUMMARIZER_MODEL_DIR = 'text_generation/summarizers/fast_abs_rl/pretrained/acl/'
# Default settings for hyperparameters of fast_abs_rl neural network
FAST_ABS_RL_SUMMARIZER_BATCH = 32
FAST_ABS_RL_SUMMARIZER_DIV = 1.0
FAST_ABS_RL_SUMMARIZER_MAX_LEN = 30
FAST_ABS_RL_SUMMARIZER_CUDA = False

# Define the output length of query_expansion function in article_extractor
ARTICLE_EXTRACTOR_QUERY_EXPANSION_SIZE = 10

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+)w6tznz(!5t6ytq#gb*9oysh&it_h2(g$y+2x990&63f&=&l$'

# as declared in NginX conf, it must match /opt/services/djangoapp/static/
STATIC_ROOT = os.path.join(
    os.path.dirname(os.path.dirname(BASE_DIR)), 'static')

# do the same for media files, it must match /opt/services/djangoapp/media/
MEDIA_ROOT = os.path.join(os.path.dirname(os.path.dirname(BASE_DIR)), 'media')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ORIGIN_ALLOW_ALL = True
ALLOWED_HOSTS = ['localhost', '130.203.136.198', 'lws-hanrahan.ist.psu.edu', '192.168.99.100', 'living-documents.ist.psu.edu', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', 'django.contrib.auth',
    'django.contrib.contenttypes', 'django.contrib.sessions',
    'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework',
    'rest_framework.authtoken', 'text_generation', 'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'living_documents_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'living_documents_server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'livingdocuments',
        'USER': 'livingdocuments',
        'PASSWORD': 'liv_docs',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# if 'test' in sys.argv:
#     DATABASES['default'] = {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(os.path.dirname(__file__), 'test.db'),
#         'TEST_NAME': os.path.join(os.path.dirname(__file__), 'test.db'),
#     }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
